SELECT C.CAR_ID, C.CAR_TYPE,TRUNCATE(((DAILY_FEE * 30) / 100) * (100 - DISCOUNT_RATE),0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON P.CAR_TYPE = C.CAR_TYPE
WHERE C.CAR_TYPE IN('세단', 'SUV')  AND DURATION_TYPE = '30일 이상' AND 
C.CAR_ID NOT IN(
SELECT DISTINCT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE,'%Y-%m') <= '2022-11'
AND DATE_FORMAT(END_DATE,'%Y-%m') >= '2022-11'
)

AND TRUNCATE(((DAILY_FEE * 30) / 100) * (100 - DISCOUNT_RATE),0) BETWEEN 500000 AND 2000000
GROUP BY C.CAR_ID
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC