-- 코드를 입력하세요

SELECT TMP.PRODUCT_ID, F.PRODUCT_NAME,(TMP.QUANTITY * F.PRICE) AS TOTAL_SALES
FROM(
    SELECT PRODUCT_ID, SUM(AMOUNT)QUANTITY
    FROM FOOD_ORDER
    WHERE DATE_FORMAT(PRODUCE_DATE, "%Y-%m") = '2022-05'
    GROUP BY PRODUCT_ID)TMP
  JOIN FOOD_PRODUCT F
 ON F.PRODUCT_ID = TMP.PRODUCT_ID
 ORDER BY TOTAL_SALES DESC, PRODUCT_ID